apiVersion: v1
kind: Service
metadata:
  name: {{ include "helloworld-app.fullname" . }}
  namespace: {{ .Values.namespace }}
spec:
  selector:
    app: {{ include "helloworld-app.name" . }}
  ports:
    - name: http
      port: 80
      targetPort: {{ .Values.port }}
  type: ClusterIP