name: Build and Deploy

on:
  push:
    branches:
      - main

jobs:
  build-and-deploy:
    name: Build and Deploy
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Log in to Docker Hub
        uses: docker/login-action@f054a8b539a109f9f41c372932f1ae047eff08c9
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}

      - name: Build Docker image
        uses: docker/build-push-action@v2
        with:
          context: .
          push: true
          tags: vumat/helloworld-app:latest

      - uses: 'actions/checkout@v3'

      - id: 'auth'
        name: 'Authenticate to Google Cloud'
        uses: 'google-github-actions/auth@v1'
        with:
          credentials_json: '${{ secrets.GCP_CREDS }}'

      - id: 'get-credentials'
        uses: 'google-github-actions/get-gke-credentials@v1'
        with:
          cluster_name: 'my-cluster'
          location: 'us-central1-a'

      # The KUBECONFIG env var is automatically exported and picked up by kubectl.
      - id: 'get-pods'
        run: 'kubectl get pods'

      - uses: google-github-actions/get-gke-credentials@fb08709ba27618c31c09e014e1d8364b02e5042e
        with:
          cluster_name: ${{ secrets.CLUSTER_NAME }}
          location: ${{ secrets.GKE_CLUSTER_REGION }}
          credentials: ${{ secrets.GCP_CREDS }}

      - name: Set kubectl context
        run: |
          gcloud container clusters get-credentials ${{ secrets.CLUSTER_NAME }} --region=${{ secrets.GKE_CLUSTER_REGION }} --project=${{ secrets.GKE_PROJECT_ID }}

      - name: Deploy to GKE using Helm
        run: |
          helm upgrade --install helloworld-app ./helm/ 
