name: Prod Deploy

on:
  pull_request:
    types: [closed]
    branches:
      - prod

jobs:

  if_merged:
    if: github.event.pull_request.merged == true
    runs-on: ubuntu-latest
    steps:
    - run: |
        echo The PR was merged

  prod-deploy:
    name: Prod Deploy
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - id: 'auth'
        name: 'Authenticate to Google Cloud'
        uses: 'google-github-actions/auth@v1'
        with:
          credentials_json: '${{ secrets.GCP_CREDS }}'

      - id: 'get-credentials'
        uses: 'google-github-actions/get-gke-credentials@v1'
        with:
          cluster_name: '${{ secrets.CLUSTER_NAME }}'
          location: '${{ secrets.GKE_CLUSTER_REGION }}'

      - name: Deploy to GKE using Helm with production values
        run: |
          helm upgrade --install helloworld-app-prod ./helm/ -f ./helm/prod-values.yaml